### Q1: (Printing and Input)
Print your name and age using two print statements.

In [1]:
print("My name is Dinesh Gurung")
print("I am 19 years old")

My name is Dinesh Gurung
I am 19 years old


### Q2: (Printing and Input)
Print the result of 10 + 20.

In [2]:
print(10 + 20)

30


### Q3: (Printing and Input)
Use `input()` to take a user's name and greet them.

In [3]:
name = input("Enter your name: ")
print("Hello, " + name + "!")

Hello, Dinesh!


### Q4: (Printing and Input)
Input two numbers and print their sum.

In [5]:
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
sum = num1 + num2
print("The sum is:", sum)

The sum is: 30


### Q5: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [6]:
color = input("Enter your favorite color: ")
print(color * 2)

WhiteWhite


### Q6: (Printing and Input)
Ask the user to input a sentence and print its length.

In [7]:
sentence = input("Enter a sentence: ")
print("The length of the sentence is:", len(sentence))

The length of the sentence is: 14


### Q7: (Variable and Data Types)
Create a variable for each type: int, float, string, bool. Print them.

In [8]:
my_int = 10
my_float = 3.14
my_string = "Hello, Python!"
my_bool = True

print("Integer:", my_int)
print("Float:", my_float)
print("String:", my_string)
print("Boolean:", my_bool)

Integer: 10
Float: 3.14
String: Hello, Python!
Boolean: True


### Q8: (Variable and Data Types)
Assign the value 10 to x and then add 5 to it. Print the result.

In [9]:
x = 10
x = x + 5
print("The result is:", x)

The result is: 15


### Q9: (Variable and Data Types)
Check the type of variable `val = 3.14`.

In [10]:
val = 3.14
print("Value:", val)
print("Type:", type(val))

Value: 3.14
Type: <class 'float'>


### Q10: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [11]:
a, b, c = 5, 10, 15

print("a =", a)
print("b =", b)
print("c =", c)

a = 5
b = 10
c = 15


### Q11: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [12]:
x = 2 + 3j
y = 4 - 2j
sum = x + y
print("The sum is:", sum)

The sum is: (6+1j)


### Q12: (Complex Numbers)
Print the real and imaginary parts of 5 + 7j.

In [13]:
z = 5 + 7j
print("Real part:", z.real)
print("Imaginary part:", z.imag)

Real part: 5.0
Imaginary part: 7.0


### Q13: (Complex Numbers)
Multiply two complex numbers: (1+2j)*(3+4j) and print the result.

In [14]:
x = 1 + 2j
y = 3 + 4j
result = x * y
print("The result is:", result)

The result is: (-5+10j)


### Q14: (If-Else and Comparisons)
Check if the number 12 is greater than 10 and print a message.

In [15]:
if 12 > 10:
    print("12 is greater than 10")

12 is greater than 10


### Q15: (If-Else and Comparisons)
Ask for an age and print whether the person is an adult or not.

In [16]:
age = int(input("Enter your age: "))

if age >= 18:
    print("You are an adult.")
else:
    print("You are not an adult.")

You are an adult.


### Q16: (If-Else and Comparisons)
Check if a number is even or odd.

In [17]:
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")

The number is odd.


### Q17: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [18]:
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

if num1 > num2:
    print("The first number is larger.")
elif num2 > num1:
    print("The second number is larger.")
else:
    print("Both numbers are equal.")

The second number is larger.


### Q18: (Loops)
Print numbers from 1 to 10 using a for loop.

In [19]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


### Q19: (Loops)
Print all even numbers from 0 to 20.

In [20]:
for num in range(0, 21, 2):
    print(num)

0
2
4
6
8
10
12
14
16
18
20


### Q20: (Loops)
Print the multiplication table of 7.

In [21]:
for i in range(1, 11):
    print("7 x", i, "=", 7 * i)

7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70


### Q21: (Loops)
Use a while loop to print numbers from 5 to 1.

In [22]:
num = 5
while num >= 1:
    print(num)
    num -= 1

5
4
3
2
1


### Q22: (Loops)
Print the characters of a string one by one using a loop.

In [23]:
my_string = "Hello"
for char in my_string:
    print(char)

H
e
l
l
o


### Q23: (String Operations)
Concatenate 'Hello' and 'World' and print.

In [24]:
str1 = "Hello"
str2 = "World"
result = str1 + str2
print(result)

HelloWorld


### Q24: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [25]:
print("Yes" * 4)

YesYesYesYes


### Q25: (String Operations)
Find the length of a string input by user.

In [26]:
user_input = input("Enter a string: ")
length = len(user_input)
print("The length of the string is:", length)

The length of the string is: 5


### Q26: (String Operations)
Access and print the first and last character of a string.

In [27]:
my_string = input("Enter a string: ")
print("First character:", my_string[0])
print("Last character:", my_string[-1])

First character: p
Last character: n


### Q27: (Lists)
Create a list of 5 fruits and print the third item.

In [28]:
fruits = ["apple", "banana", "cherry", "date", "elderberry"]
print("The third fruit is:", fruits[2])

The third fruit is: cherry


### Q28: (Lists)
Add 'mango' to the list and print.

In [29]:
fruits = ["apple", "banana", "cherry", "date", "elderberry"]
fruits.append("mango")
print(fruits)

['apple', 'banana', 'cherry', 'date', 'elderberry', 'mango']


### Q29: (Lists)
Remove the first item of the list and print the rest.

In [30]:
fruits = ["apple", "banana", "cherry", "date", "elderberry", "mango"]
fruits.pop(0)  # Removes the first item
print(fruits)

['banana', 'cherry', 'date', 'elderberry', 'mango']


### Q30: (Lists)
Sort a list of numbers in descending order.

In [31]:
numbers = [5, 2, 9, 1, 7]
numbers.sort(reverse=True)
print(numbers)

[9, 7, 5, 2, 1]


### Q31: (Lists)
Print every second item from a list using slicing.

In [32]:
my_list = [10, 20, 30, 40, 50, 60, 70]
print(my_list[1::2])

[20, 40, 60]


### Q32: (Tuples)
Create a tuple with 4 numbers and print its last item.

In [33]:
my_tuple = (10, 20, 30, 40)
print("The last item is:", my_tuple[-1])

The last item is: 40


### Q33: (Tuples)
Try changing the value of an item in a tuple and observe the error.

In [ ]:
my_tuple = (10, 20, 30, 40)
my_tuple[1] = 50  

TypeError: 'tuple' object does not support item assignment

### Q34: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [1]:
my_tuple = (10, 20, 30)
my_list = list(my_tuple)
my_list[1] = 25
new_tuple = tuple(my_list)
print(new_tuple)

(10, 25, 30)


### Q35: (Sets)
Create a set of 3 elements and add one more element.

In [2]:
my_set = {1, 2, 3}
my_set.add(4)
print(my_set)

{1, 2, 3, 4}


### Q36: (Sets)
Try adding a duplicate and print the set.

In [3]:
my_set = {1, 2, 3}
my_set.add(2)
print(my_set)

{1, 2, 3}


### Q37: (Sets)
Perform union of two sets {1,2,3} and {3,4,5}.

In [4]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1.union(set2)
print(union_set)

{1, 2, 3, 4, 5}


### Q38: (Dictionaries)
Create a dictionary for a student with name, age, grade. Print the dictionary.

In [5]:
student = {
    "name": "John",
    "age": 16,
    "grade": "10th"
}
print(student)

{'name': 'John', 'age': 16, 'grade': '10th'}


### Q39: (Dictionaries)
Access the age from the dictionary.

In [6]:
print(student["age"])

16


### Q40: (Dictionaries)
Update the grade of the student.

In [7]:
student["grade"] = "11th"
print(student)

{'name': 'John', 'age': 16, 'grade': '11th'}


### Q41: (Dictionaries)
Add a new key 'subject' to the dictionary.

In [8]:
student["subject"] = "Math"
print(student)

{'name': 'John', 'age': 16, 'grade': '11th', 'subject': 'Math'}


### Q42: (Indexing and Slicing)
Create a list of numbers and print elements from index 1 to 4.

In [9]:
numbers = [10, 20, 30, 40, 50, 60]
print(numbers[1:5])

[20, 30, 40, 50]


### Q43: (Indexing and Slicing)
Access every second element in the list.

In [10]:
numbers = [10, 20, 30, 40, 50, 60]
print(numbers[::2])

[10, 30, 50]


### Q44: (Indexing and Slicing)
Print the last three characters of the string 'Programming'.

In [11]:
s = "Programming"
print(s[-3:])

ing


### Q45: (Nested Structures)
Create a nested list and print the second element of the first list.

In [12]:
nested_list = [[10, 20, 30], [40, 50, 60]]
print(nested_list[0][1])

20


### Q46: (Nested Structures)
Create a nested dictionary and access a nested value.

In [13]:
student = {
    "name": "Alice",
    "age": 17,
    "grades": {
        "math": 90,
        "science": 85
    }
}

print(student["grades"]["math"])

90


### Q47: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [14]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Q48: (NumPy Basics)
Create a 2D array with shape (2,3).

In [15]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
print("Shape:", arr.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


### Q49: (NumPy Basics)
Print the shape and dtype of an array.

In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Data type:", arr.dtype)

Shape: (2, 3)
Data type: int64


### Q50: (NumPy Basics)
Use np.linspace to create 5 values from 1 to 10.

In [17]:
import numpy as np

values = np.linspace(1, 10, 5)
print(values)

[ 1.    3.25  5.5   7.75 10.  ]


### Q51: (NumPy Basics)
Generate a random array of shape (3,3).

In [18]:
import numpy as np

random_array = np.random.rand(3, 3)
print(random_array)

[[0.9331292  0.14224599 0.35510232]
 [0.53983274 0.66783983 0.68903975]
 [0.61803321 0.52626393 0.45854176]]


### Q52: (NumPy Basics)
Find the maximum and mean of a numpy array.

In [19]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

max_value = arr.max()
mean_value = arr.mean()

print("Maximum:", max_value)
print("Mean:", mean_value)

Maximum: 50
Mean: 30.0


### Q53: (NumPy Basics)
Access element at row 1, col 2 in a 2D array.

In [20]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr[1, 2])

60


### Q54: (NumPy Basics)
Flatten a 2D array.

In [21]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


### Q55: (NumPy Basics)
Stack two arrays vertically.

In [22]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked = np.vstack((arr1, arr2))
print(stacked)

[[1 2 3]
 [4 5 6]]


### Q56: (NumPy Basics)
Slice the first two rows of a 2D numpy array.

In [23]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

first_two_rows = arr[:2, :]
print(first_two_rows)

[[10 20 30]
 [40 50 60]]


### Q57: (NumPy Basics)
Slice the first two rows of a 2D numpy array.

In [24]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

first_two_rows = arr[:2]
print(first_two_rows)

[[10 20 30]
 [40 50 60]]


### Q58: (NumPy Basics)
Print the shape and dtype of an array.

In [25]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Data type:", arr.dtype)

Shape: (2, 3)
Data type: int64


### Q59: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [26]:
print("Yes" * 4)

YesYesYesYes


### Q60: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [27]:
a, b, c = 10, 20, 30
print(a, b, c)

10 20 30


### Q61: (Dictionaries)
Add a new key 'subject' to the dictionary.

In [28]:
student = {
    "name": "John",
    "age": 16,
    "grade": "10th"
}

student["subject"] = "Math"
print(student)

{'name': 'John', 'age': 16, 'grade': '10th', 'subject': 'Math'}


### Q62: (Variable and Data Types)
Assign the value 10 to x and then add 5 to it. Print the result.

In [29]:
x = 10
x = x + 5
print(x)

15


### Q63: (Nested Structures)
Create a nested list and print the second element of the first list.

In [30]:
nested_list = [[1, 2, 3], [4, 5, 6]]
print(nested_list[0][1])

2


### Q64: (Loops)
Print the characters of a string one by one using a loop.

In [31]:
s = "Hello"

for char in s:
    print(char)

H
e
l
l
o


### Q65: (Sets)
Try adding a duplicate and print the set.

In [32]:
my_set = {1, 2, 3}
my_set.add(2)  # Adding duplicate
print(my_set)

{1, 2, 3}


### Q66: (NumPy Basics)
Flatten a 2D array.

In [33]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


### Q67: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
# Your answer here

### Q68: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [ ]:
# Your answer here

### Q69: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
# Your answer here

### Q70: (If-Else and Comparisons)
Check if a number is even or odd.

In [ ]:
# Your answer here

### Q71: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [ ]:
# Your answer here

### Q72: (Loops)
Use a while loop to print numbers from 5 to 1.

In [ ]:
# Your answer here

### Q73: (If-Else and Comparisons)
Check if the number 12 is greater than 10 and print a message.

In [ ]:
# Your answer here

### Q74: (Indexing and Slicing)
Access every second element in the list.

In [ ]:
# Your answer here

### Q75: (Loops)
Use a while loop to print numbers from 5 to 1.

In [ ]:
# Your answer here

### Q76: (Printing and Input)
Print the result of 10 + 20.

In [ ]:
# Your answer here

### Q77: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
# Your answer here

### Q78: (Lists)
Remove the first item of the list and print the rest.

In [ ]:
# Your answer here

### Q79: (NumPy Basics)
Use np.linspace to create 5 values from 1 to 10.

In [ ]:
# Your answer here

### Q80: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [ ]:
# Your answer here

### Q81: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
# Your answer here

### Q82: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [ ]:
# Your answer here

### Q83: (Dictionaries)
Access the age from the dictionary.

In [ ]:
# Your answer here

### Q84: (Lists)
Create a list of 5 fruits and print the third item.

In [ ]:
# Your answer here

### Q85: (NumPy Basics)
Stack two arrays vertically.

In [ ]:
# Your answer here

### Q86: (Loops)
Use a while loop to print numbers from 5 to 1.

In [ ]:
# Your answer here

### Q87: (Lists)
Remove the first item of the list and print the rest.

In [ ]:
# Your answer here

### Q88: (Lists)
Create a list of 5 fruits and print the third item.

In [ ]:
# Your answer here

### Q89: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
# Your answer here

### Q90: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [ ]:
# Your answer here

### Q91: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [ ]:
# Your answer here

### Q92: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [ ]:
# Your answer here

### Q93: (Variable and Data Types)
Check the type of variable `val = 3.14`.

In [ ]:
# Your answer here

### Q94: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [ ]:
# Your answer here

### Q95: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [ ]:
# Your answer here

### Q96: (Sets)
Try adding a duplicate and print the set.

In [ ]:
# Your answer here

### Q97: (Dictionaries)
Access the age from the dictionary.

In [ ]:
# Your answer here

### Q98: (Lists)
Add 'mango' to the list and print.

In [ ]:
# Your answer here

### Q99: (Sets)
Create a set of 3 elements and add one more element.

In [34]:
my_set = {1, 2, 3}
my_set.add(4)
print(my_set)

{1, 2, 3, 4}


### Q100: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [ ]:
# Your answer here