## Section A: Theoretical Questions

### What is the difference between a list, tuple, and set in Python? Give one use-case for each.

A list in Python is an ordered and mutable collection that allows duplicate elements. We can add, remove, or change items in a list, making it ideal for 
situations where the data may need to be updated frequently, like managing a to-do list or a collection of user inputs. A tuple, on the other hand, is also
ordered but immutable, meaning once created, its contents cannot be changed. Tuples are useful for storing fixed data that should remain constant 
throughout the program, such as GPS coordinates or configuration settings. Lastly, a set is an unordered collection of unique elements — it automatically
removes duplicates and does not maintain any order. Sets are perfect when you need to keep track of distinct items, like unique visitors to a website or 
unique tags in a collection. Each of these data types serves different purposes depending on whether you need mutability, order, or uniqueness.

### Explain how type casting is useful in handling user input.

Type casting is very useful when handling user input because input from users is typically received as a string by default. However, often we need to work 
with data in different types, like integers or floats, to perform calculations or comparisons. By using type casting, we convert the input string into the
required data type, making it possible to use that data correctly in our program. For example, if a user enters their age, it comes in as a string like 
"25". To do arithmetic operations or comparisons, you need to convert it to an integer using int(). Without this conversion, mathematical operations would 
cause errors or behave incorrectly. Similarly, for decimal numbers, converting input to a float using float() allows precise calculations.

In summary, type casting helps ensure that user inputs are interpreted and used in the correct data format, making programs more robust and error-free.

### What is string slicing? Give an example.

String slicing is a way to extract a portion (substring) of a string by specifying a range of indices. It lets us to select parts of a string by providing a 
start index, an end index (exclusive), and optionally a step.
Example: s = "Hello, World!"
         print(s[0:5])    # Output: Hello
         print(s[7:12])   # Output: World
         print(s[::2]).   # Output: Hlo ol!
    ->	s[0:5] extracts characters from index 0 up to (but not including) index 5.
    ->	s[7:12] extracts characters from index 7 up to 12.
	->	s[::2] extracts every second character from the whole string.    

### Compare 1D vs 2D arrays in the context of NumPy. Why is it important in data science?

In the context of NumPy, the difference between 1D and 2D arrays is primarily about structure and how data is accessed or represented. More of a comparison
between the 1D and 2D arrays is given below:
A 1D array is a simple list of elements arranged in a single row. For example: arr = np.array([1, 2, 3, 4])
This is like a single line of data, which is useful for storing a series of values such as scores or labels.

A 2D array, on the other hand, is like a grid or table, consisting of rows and columns. For example: arr = np.array([[1, 2], [3, 4]])
This structure is more powerful for representing data in matrix form, such as datasets with multiple features (columns) and observations (rows).

Data science is important in th econtext of NumPy, datasets are usually structured as tables — like rows of customer records with multiple attributes 
(age, income, etc.). A 2D array is ideal for representing such data. Understanding the difference allows data scientists to apply the right operationslike 
matrix multiplication, slicing rows/columns, and feeding data into machine learning models — efficiently.

### Why is indentation important in Python? What happens if you ignore it?

Indentation is very important in Python because it defines the structure of the code especially which lines belong to which blocks, like loops, conditionals,
functions, and classes. Unlike many other languages that use braces {} or keywords to mark blocks of code, Python uses indentation (spaces or tabs) to group
statements. It is important because it tells Python which code is inside a loop, if statement, function, etc and makes code readable and organized.It also 
prevents logic errors by clearly showing the flow of control.
If we don’t use proper indentation, Python will raise an IndentationError or may run the code incorrectly, leading to logic errors.
Example:
        # Correctly indented
    if True:
       print("This is true")

       # Incorrectly indented
     if True:
     print("This will cause an error")

## Section B: Coding Exercises


### User Input & Type Casting
### Take the age and height (in cm) of a user as input and print a message like:
### "You are 23 years old and 170.5 cm tall."


In [2]:
# Take age and height as input
age = input("Enter your age: ")
height = input("Enter your height in cm: ")

# Print the message
print(f"You are {age} years old and {height} cm tall.")

You are 19 years old and 167 cm tall.



### Given a string s = "DataScience", print:

### (a) First 4 characters

### (b) Last 3 characters

### (c) Every second character

In [3]:
s = "DataScience"

# (a) First 4 characters
print("First 4 characters:", s[:4])

# (b) Last 3 characters
print("Last 3 characters:", s[-3:])

# (c) Every second character
print("Every second character:", s[::2])

First 4 characters: Data
Last 3 characters: nce
Every second character: DtSine



### Create a list of numbers from 1 to 10. Convert it to a tuple and print the square of each number using a loop.

In [4]:
num_list = list(range(1, 11))
num_tuple = tuple(num_list)

for num in num_tuple:
    print(f"The square of {num} is {num ** 2}")

The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25
The square of 6 is 36
The square of 7 is 49
The square of 8 is 64
The square of 9 is 81
The square of 10 is 100


### Given two sets:
### A = {1, 2, 3, 4, 5}, B = {4, 5, 6, 7},

### Print the union and intersection of the sets.

### Remove 3 from set A.

In [5]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7}

union_set = A.union(B)
print("Union of A and B:", union_set)

intersection_set = A.intersection(B)
print("Intersection of A and B:", intersection_set)

A.discard(3)
print("Set A after removing 3:", A)

Union of A and B: {1, 2, 3, 4, 5, 6, 7}
Intersection of A and B: {4, 5}
Set A after removing 3: {1, 2, 4, 5}



### (a) Create a NumPy array from a user input list.
### (b) Create a 2D NumPy array of shape (3, 3) and fill it with numbers 1 to 9.
### (c) Print the first row, last column, and the transpose of the array.

In [6]:
import numpy as np

# (a) Create a NumPy array from a user input list
user_input = input("Enter numbers separated by spaces: ")
num_list = [int(x) for x in user_input.split()]
arr1 = np.array(num_list)
print("1D NumPy array from input:", arr1)

# (b) Create a 2D NumPy array of shape (3, 3) with numbers 1 to 9
arr2 = np.arange(1, 10).reshape(3, 3)
print("\n2D NumPy array (3x3):\n", arr2)

# (c) Print the first row, last column, and transpose of the array
print("\nFirst row:", arr2[0])
print("Last column:", arr2[:, -1])
print("Transpose:\n", arr2.T)

1D NumPy array from input: [10 20 30 40]

2D NumPy array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

First row: [1 2 3]
Last column: [3 6 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Section C: BrainStorming

### Why are NumPy arrays preferred over lists in data science? Mention two reasons with examples.

In [ ]:
import numpy as np
import time

list_data = list(range(1000000))
start = time.time()
list_squared = [x**2 for x in list_data]
print("List time:", time.time() - start)

arr_data = np.array(list_data)
start = time.time()
arr_squared = arr_data ** 2
print("NumPy time:", time.time() - start)

List time: 0.04581117630004883
NumPy time: 0.002064228057861328


### Suppose you want to store multiple temperature readings over several days, where each day has different numbers of readings. Which Python data structure would you choose and why?

If each day has a different number of temperature readings, so to store these multiple temperature readings I would choose list of lists Python data structure because a list can store any number of elements and also is dynamic in size. It is also easy to access individual readings.

In [ ]:
temperature_readings = [
    [22.5, 23.0, 21.8],       # Day 1: 3 readings
    [20.1, 19.8],             # Day 2: 2 readings
    [25.0, 26.3, 24.5, 23.9]  # Day 3: 4 readings
]
print(temperature_readings[0][1]) 

23.0


### Create a function analyze_array(arr) that:

### Takes a NumPy array as input

### Prints the shape, mean, and standard deviation of the array.

In [ ]:
import numpy as np

def analyze_array(arr):
    print("Shape of array:", arr.shape)
    print("Mean of array:", np.mean(arr))
    print("Standard deviation of array:", np.std(arr))
#Example:
data = np.array([[1, 2, 3], [4, 5, 6]])
analyze_array(data)

Shape of array: (2, 3)
Mean of array: 3.5
Standard deviation of array: 1.707825127659933


### Given a list of 10 integers, write a loop to check which numbers are divisible by both 2 and 3. Store them in a set.

In [3]:
numbers = [12, 7, 18, 20, 24, 5, 30, 33, 36, 40]  # Example list of 10 integers
divisible_by_2_and_3 = set()

for num in numbers:
    if num % 2 == 0 and num % 3 == 0:
        divisible_by_2_and_3.add(num)

print(divisible_by_2_and_3)

{36, 12, 18, 24, 30}
